### ISSUE TITLE
SevenZipFile does not accept Flask file uploads

### ISSUE THREAD

**Issue by freddrake** [miurahr/py7zr#232]
**SevenZipFile** won't accept a **werkzeug.datastructures.FileStorage** as a file object.  This is used to represent a file upload in the **Flask** framework.

The **FileStorage** (or anything not recognized as a path) should be treated like any other binary file.

**Environment:**
 - OS: Ubuntu Linux 18.04.5
 - Python 3.8.5
 - py7zr version: 0.9.5

**Comment by miurahr** [comment]
Could you provide test data and test code you consider it to be passed.

SevenZipFile accept a file object which has  methods,  read() and seek() for extraction, and write() and seek() for compression, because of 7zip format nature that require random access to file object, which come from a meta data placement, storing metadata at end of file and then store its CRC  checksum at first of file, it force the library seeking from end of file to start of file.

cf. https://py7zr.readthedocs.io/en/latest/archive_format.html

**Comment by freddrake** [comment]
I've not been able to reproduce this since I got this the first time, so I presume I was doing something improperly in my own code at the time.

Closing as user error.
