### ISSUE TITLE
Don't include the whole license text in the 'license' field

### ISSUE THREAD

**Issue by alexitx** [miurahr/py7zr#435]
The text of the LGPLv2 license overflows on the PyPI page and also severely affects the loading of the PyPI and GitHub page on Firefox browsers because of the shields.io badge in the README. The badge is also not rendered on Chromium browsers.

https://github.com/miurahr/py7zr/blob/55342c5036117921c8ab71ecf3972a9b348c7a84/pyproject.toml#L6

According to the [docs](https://setuptools.pypa.io/en/latest/references/keywords.html) there is a `license_files` keyword that should be used for the whole license file. The `license` keyword is generally used only for the license name or abbreviation, such as `GNU Lesser General Public License, version 2.1` or `LGPL-2.1`

**Comment by miurahr** [comment]
PEP-621 defined `license` field as
> Format: Table
Core metadata: License (link)
Synonyms
Flit: license (link)
Poetry: license (link)
Setuptools: license, license_file, license_files (link)
The table may have one of two keys. The file key has a string value that is a relative file path to the file which contains the license for the project. Tools MUST assume the file’s encoding is UTF-8. The text key has a string value which is the license of the project whose meaning is that of the License field from the core metadata. These keys are mutually exclusive, so a tool MUST raise an error if the metadata specifies both keys.


@alexitx said:
> According to the [docs](https://setuptools.pypa.io/en/latest/references/keywords.html) there is a license_files keyword that should be used for the whole license file.

It seems a PyPI issue that make index page overflow. because  `license = { file = "LICENSE" }` in `pyproject.toml` is as same as  `license_files = LICENSE` in `setup.cfg`.

**Comment by alexitx** [comment]
> It seems a PyPI issue that make index page overflow. because license = { file = "LICENSE" } in pyproject.toml is as same as license_files = LICENSE in setup.cfg.

Hmm, didn't know that as I've always used setup.cfg and not pyproject.toml for setting metadata.

Anyhow, I reported the issue of Firefox freezing when loading large SVGs which was my main concern when I couldn't load neither the PyPI nor the GitHub page of py7zr.

But thanks for addressing this!
